{
 "title": "HelpDev Metrics App",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Http Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_server_requests_seconds_count{application=\"$application\"}[1m]))",
     "legendFormat": "Http status: {{status}}"
    }
   ]
  },
  {
   "title": "Time método doProcess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hello_get_do_process_timer_seconds_sum{application=\"$application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceded Lenght limit",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(length) (hello_get_name_length_limit_total{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}